import {contact_us_form_types} from "@/types";

export const site_languages = [
  {
    label: "English",
    value: "en",
  },
  {
    label: "فارسی",
    value: "fa",
  },
  {
    label: "Arabic",
    value: "ar",
  },
];
// src/constants/services.ts

export const SERVICES = [
  {id: "stone", label: "سنگ‌شکن برون‌اندامی"},
  {id: "endoscopy", label: "آندوسکوپی فوقانی"},
  {id: "colonoscopy", label: "کولونوسکوپی کامل"},
  {id: "endo-colono", label: "آندوسکوپی و کولونوسکوپی هم‌زمان"},
  {id: "dialysis1", label: "دیالیز ویژه بیماران بین‌الملل (یک‌جلسه‌ای)"},
  {id: "dialysis3", label: "دیالیز ویژه بیماران بین‌الملل کوتاه‌مدت (3 جلسه)"},
  {id: "dialysis6", label: "دیالیز ویژه بیماران بین‌الملل هفتگی (6 جلسه)"},
  {id: "dialysis12", label: "دیالیز ویژه بیماران بین‌الملل ماهانه (12 جلسه)"},
  {id: "uterus", label: "جراحی سرطان رحم یا دهانه رحم"},
  {id: "ovary", label: "جراحی سرطان تخمدان"},
  {id: "women-screen", label: "غربالگری جامع زنان"},
  {id: "breast-screen", label: "غربالگری بیماری‌های پستان"},
  {id: "angiography", label: "آنژیوگرافی قلب"},
  {id: "stent", label: "آنژیوپلاستی + استنت‌گذاری (فنر قلب)"},
  {id: "ep-study", label: "تست الکتروفیزیولوژی قلب"},
  {id: "ablation", label: "ابلیشن قلبی"},
  {id: "crt", label: "نصب دستگاه‌های قلبی (CRT)"},
  {id: "icd", label: "نصب دستگاه‌های قلبی (ICD)"},
  {id: "pacemaker", label: "نصب دستگاه‌های قلبی (Pacemaker)"},
  {id: "rhinoplasty", label: "رینوپلاستی (جراحی بینی)"},
  {id: "lipo", label: "لیپوساکشن / لیپوماتیک (شکم، پهلو، ران)"},
  {id: "abdominoplasty", label: "ابدومینوپلاستی (جراحی زیبایی شکم)"},
  {id: "blepharoplasty", label: "بلفاروپلاستی (جراحی پلک بالا و پایین)"},
  {id: "facelift", label: "لیفت صورت و گردن"},
  {id: "breast-pro", label: "پروتز سینه / لیفت سینه (با پروتز)"},
  {id: "breast-no-pro", label: "پروتز سینه / لیفت سینه (بدون پروتز)"},
  {id: "hair", label: "کاشت مو"},
  {id: "fat", label: "تزریق چربی به صورت یا بدن"},
  {id: "septoplasty", label: "سپتوپلاستی (اصلاح انحراف تیغه بینی)"},
  {id: "tonsil", label: "آدنوئیدکتومی و/یا لوزه‌برداری"},
  {id: "polyp", label: "پولیپ بینی یا سینوس (پولیپکتومی)"},
  {id: "path-bio", label: "پاتولوژی (نمونه‌های بافتی)"},
  {id: "path-cyto1", label: "پاتولوژی (سیتولوژی - پاپ‌اسمیر ساده)"},
  {id: "path-cyto2", label: "پاتولوژی (سیتولوژی - پاپ‌اسمیر + مایع پایه)"},
  {id: "path-fna", label: "پاتولوژی (سیتولوژی - گزارش FNA+)"},
  {id: "path-ihc1", label: "پاتولوژی (ایمونوهیستوشیمی - هر مارکر)"},
  {
    id: "path-ihc2",
    label: "پاتولوژی (ایمونوهیستوشیمی - پکیج کامل سرطان پستان)",
  },
  {id: "path-slide", label: "پاتولوژی (بازخوانی اسلاید)"},
  {id: "path-block", label: "پاتولوژی (تهیه بلوک و اسلاید اضافی)"},
];

// src/constants/packageServices.ts

export const PACKAGE_SERVICES = [
  {
    id: 1,
    slug: "digestive-package",
    title: "پکیج گوارش",
    content: [
      "آندوسکوپی فوقانی",
      "کولونوسکوپی کامل",
      "آندوسکوپی و کولونوسکوپی هم‌زمان",
    ],
  },
  {
    id: 2,
    slug: "hysterectomy",
    title: "پکیج هیسترتومی",
    content: ["جراحی سرطان رحم یا دهانه رحم", "جراحی سرطان تخمدان"],
  },
  {
    id: 3,
    slug: "cardiac",
    title: "پکیج قلب",
    content: [
      "آنژیوگرافی قلب",
      "آنژیوپلاستی + استنت‌گذاری (فنر قلب)",
      "تست الکتروفیزیولوژی قلب",
      "ابلیشن قلبی",
      "نصب دستگاه‌های قلبی (CRT)",
      "نصب دستگاه‌های قلبی (ICD)",
      "نصب دستگاه‌های قلبی (Pacemaker)",
      "CABG",
    ],
  },
  {
    id: 4,
    slug: "beauty",
    title: "پکیج زیبایی",
    content: [
      "لیپوساکشن / لیپوماتیک (شکم، پهلو، ران)",
      "ابدومینوپلاستی (جراحی زیبایی شکم)",
      "بلفاروپلاستی (جراحی پلک بالا و پایین)",
      "لیفت صورت و گردن",
      "پروتز سینه / لیفت سینه (با پروتز)",
      "پروتز سینه / لیفت سینه (بدون پروتز)",
      "کاشت مو",
      "اسلیو",
      "تزریق چربی به صورت یا بدن",
    ],
  },
  {
    id: 5,
    slug: "orthopedic",
    title: "پکیج ارتوپدی",
    content: ["تعویض مفصل ران", "تعویض مفصل زانو"],
  },
  {
    id: 6,
    slug: "brain-surgery",
    title: "پکیج جراحی مغز",
    content: [
      "جراحی ستون فقرات (فیوژن)",
      "جراحی ستون فقرات (لامینکتومی)",
      "جراحی ستون فقرات (دیستکتومی)",
      "کرانيوتومی",
      "جراحی قاعده جمجمه",
      "جراحی تومورهای مغزی",
    ],
  },
  {
    id: 7,
    slug: "ent",
    title: "پکیج گوش و حلق و بینی",
    content: [
      "سپتوپلاستی (اصلاح انحراف تیغه بینی)",
      "آدنوئیدکتومی و/یا لوزه‌برداری",
      "پلیپ بینی یا سینوس (پولیپکتومی)",
      "رینوپلاستی (جراحی بینی)",
    ],
  },
];

export const MEDICAL_PACKAGES = PACKAGE_SERVICES.map((item) => ({
  id: item.id,
  slug: item.slug,
  title: item.title,
}));

export const PHONE_NUMBERS = Object.freeze({
  ipd_technician: {
    label: "09385745269",
    href: "+989385745269",
  },
  hospital: {
    label: "011-4492",
    href: "+09811-4492",
  },
});

export const Page_header_slider = Object.freeze({
  hospital_name: {
    fa: "بیمارستان فوق تخصصی شمال آمل",
    en: "Shomal Super Specialty Hospital, Amol",
    ar: "مستشفى شمال التخصصي الفائق – آمل",
  },
  n1_authority_validation: {
    fa: "کسب رتبه یک اعتباربخشی",
    en: "Achieved Grade A National Accreditation",
    ar: "الحصول على التصنيف الأول في الاعتماد الوطني",
  },
});

export const contact_us_form: contact_us_form_types = Object.freeze({
  fields: {
    first_name: {
      type: "text",
      as: "input",
    },
    last_name: {
      type: "text",
      as: "input",
    },
    phone_number: {
      type: "text",
      as: "input",
    },
    email: {
      type: "text",
      as: "input",
    },
    age: {
      type: "number",
      as: "input",
    },
    sex: {
      type: "select",
      as: "select",
    },
    country: {
      type: "select",
      as: "select",
    },
    message: {
      type: "text",
      as: "textarea",
    },
  },
});

export const Expertises = [
  {
    id: 1,
    name: {
      fa: "ارتوپدی",
      en: "Orthopedics",
      ar: "جراحة العظام",
    },
  },
  {
    id: 2,
    name: {
      fa: "جراحی عمومی",
      en: "General Surgery",
      ar: "الجراحة العامة",
    },
  },
  {
    id: 3,
    name: {
      fa: "قلب و عروق",
      en: "Cardiology",
      ar: "أمراض القلب",
    },
  },
  {
    id: 4,
    name: {
      fa: "زنان و زایمان",
      en: "Obstetrics and Gynecology",
      ar: "أمراض النساء والتوليد",
    },
  },
  {
    id: 5,
    name: {
      fa: "مغز و اعصاب",
      en: "Neurosurgery / Neurology",
      ar: "جراحة الأعصاب / طب الأعصاب",
    },
  },
  {
    id: 6,
    name: {
      fa: "گوارش",
      en: "Gastroenterology",
      ar: "أمراض الجهاز الهضمي",
    },
  },
  {
    id: 7,
    name: {
      fa: "کلیه و مجاری ادراری",
      en: "Urology",
      ar: "أمراض الكلى والجهاز البولي",
    },
  },

  {
    id: 8,
    name: {
      fa: "گوش و حلق و بینی",
      en: "ENT (Ear, Nose, and Throat)",
      ar: "أمراض الأنف والأذن والحنجرة",
    },
  },
];

export const all_countries = [
  {label: "Afghanistan", value: "afghanistan", code: "+93"},
  {label: "Albania", value: "albania", code: "+355"},
  {label: "Algeria", value: "algeria", code: "+213"},
  {label: "American Samoa", value: "american-samoa", code: "+1-684"},
  {label: "Andorra", value: "andorra", code: "+376"},
  {label: "Angola", value: "angola", code: "+244"},
  {label: "Anguilla", value: "anguilla", code: "+1-264"},
  {label: "Antigua and Barbuda", value: "antigua-and-barbuda", code: "+1-268"},
  {label: "Argentina", value: "argentina", code: "+54"},
  {label: "Armenia", value: "armenia", code: "+374"},
  {label: "Aruba", value: "aruba", code: "+297"},
  {label: "Australia", value: "australia", code: "+61"},
  {label: "Austria", value: "austria", code: "+43"},
  {label: "Azerbaijan", value: "azerbaijan", code: "+994"},
  {label: "Bahamas", value: "bahamas", code: "+1-242"},
  {label: "Bahrain", value: "bahrain", code: "+973"},
  {label: "Bangladesh", value: "bangladesh", code: "+880"},
  {label: "Barbados", value: "barbados", code: "+1-246"},
  {label: "Belarus", value: "belarus", code: "+375"},
  {label: "Belgium", value: "belgium", code: "+32"},
  {label: "Belize", value: "belize", code: "+501"},
  {label: "Benin", value: "benin", code: "+229"},
  {label: "Bhutan", value: "bhutan", code: "+975"},
  {label: "Bolivia", value: "bolivia", code: "+591"},
  {
    label: "Bosnia and Herzegovina",
    value: "bosnia-and-herzegovina",
    code: "+387",
  },
  {label: "Botswana", value: "botswana", code: "+267"},
  {label: "Brazil", value: "brazil", code: "+55"},
  {label: "Brunei", value: "brunei", code: "+673"},
  {label: "Bulgaria", value: "bulgaria", code: "+359"},
  {label: "Burkina Faso", value: "burkina-faso", code: "+226"},
  {label: "Burundi", value: "burundi", code: "+257"},
  {label: "Cabo Verde", value: "cabo-verde", code: "+238"},
  {label: "Cambodia", value: "cambodia", code: "+855"},
  {label: "Cameroon", value: "cameroon", code: "+237"},
  {label: "Canada", value: "canada", code: "+1"},
  {
    label: "Central African Republic",
    value: "central-african-republic",
    code: "+236",
  },
  {label: "Chad", value: "chad", code: "+235"},
  {label: "Chile", value: "chile", code: "+56"},
  {label: "China", value: "china", code: "+86"},
  {label: "Colombia", value: "colombia", code: "+57"},
  {label: "Comoros", value: "comoros", code: "+269"},
  {label: "Congo", value: "congo", code: "+242"},
  {
    label: "Congo, Democratic Republic of the",
    value: "congo-democratic-republic",
    code: "+243",
  },
  {label: "Costa Rica", value: "costa-rica", code: "+506"},
  {label: "Croatia", value: "croatia", code: "+385"},
  {label: "Cuba", value: "cuba", code: "+53"},
  {label: "Cyprus", value: "cyprus", code: "+357"},
  {label: "Czech Republic", value: "czech-republic", code: "+420"},
  {label: "Denmark", value: "denmark", code: "+45"},
  {label: "Djibouti", value: "djibouti", code: "+253"},
  {label: "Dominica", value: "dominica", code: "+1-767"},
  {label: "Dominican Republic", value: "dominican-republic", code: "+1-809"},
  {label: "Ecuador", value: "ecuador", code: "+593"},
  {label: "Egypt", value: "egypt", code: "+20"},
  {label: "El Salvador", value: "el-salvador", code: "+503"},
  {label: "Equatorial Guinea", value: "equatorial-guinea", code: "+240"},
  {label: "Eritrea", value: "eritrea", code: "+291"},
  {label: "Estonia", value: "estonia", code: "+372"},
  {label: "Eswatini", value: "eswatini", code: "+268"},
  {label: "Ethiopia", value: "ethiopia", code: "+251"},
  {label: "Fiji", value: "fiji", code: "+679"},
  {label: "Finland", value: "finland", code: "+358"},
  {label: "France", value: "france", code: "+33"},
  {label: "Gabon", value: "gabon", code: "+241"},
  {label: "Gambia", value: "gambia", code: "+220"},
  {label: "Georgia", value: "georgia", code: "+995"},
  {label: "Germany", value: "germany", code: "+49"},
  {label: "Ghana", value: "ghana", code: "+233"},
  {label: "Greece", value: "greece", code: "+30"},
  {label: "Grenada", value: "grenada", code: "+1-473"},
  {label: "Guatemala", value: "guatemala", code: "+502"},
  {label: "Guinea", value: "guinea", code: "+224"},
  {label: "Guinea-Bissau", value: "guinea-bissau", code: "+245"},
  {label: "Guyana", value: "guyana", code: "+592"},
  {label: "Haiti", value: "haiti", code: "+509"},
  {label: "Honduras", value: "honduras", code: "+504"},
  {label: "Hungary", value: "hungary", code: "+36"},
  {label: "Iceland", value: "iceland", code: "+354"},
  {label: "India", value: "india", code: "+91"},
  {label: "Indonesia", value: "indonesia", code: "+62"},
  {label: "Iran", value: "iran", code: "+98"},
  {label: "Iraq", value: "iraq", code: "+964"},
  {label: "Ireland", value: "ireland", code: "+353"},
  {label: "Israel", value: "israel", code: "+972"},
  {label: "Italy", value: "italy", code: "+39"},
  {label: "Jamaica", value: "jamaica", code: "+1-876"},
  {label: "Japan", value: "japan", code: "+81"},
  {label: "Jordan", value: "jordan", code: "+962"},
  {label: "Kazakhstan", value: "kazakhstan", code: "+7"},
  {label: "Kenya", value: "kenya", code: "+254"},
  {label: "Kiribati", value: "kiribati", code: "+686"},
  {label: "Kuwait", value: "kuwait", code: "+965"},
  {label: "Kyrgyzstan", value: "kyrgyzstan", code: "+996"},
  {label: "Laos", value: "laos", code: "+856"},
  {label: "Latvia", value: "latvia", code: "+371"},
  {label: "Lebanon", value: "lebanon", code: "+961"},
  {label: "Lesotho", value: "lesotho", code: "+266"},
  {label: "Liberia", value: "liberia", code: "+231"},
  {label: "Libya", value: "libya", code: "+218"},
  {label: "Liechtenstein", value: "liechtenstein", code: "+423"},
  {label: "Lithuania", value: "lithuania", code: "+370"},
  {label: "Luxembourg", value: "luxembourg", code: "+352"},
  {label: "Macau", value: "macau", code: "+853"},
  {label: "North Macedonia", value: "north-macedonia", code: "+389"},
  {label: "Madagascar", value: "madagascar", code: "+261"},
  {label: "Malawi", value: "malawi", code: "+265"},
  {label: "Malaysia", value: "malaysia", code: "+60"},
  {label: "Maldives", value: "maldives", code: "+960"},
  {label: "Mali", value: "mali", code: "+223"},
  {label: "Malta", value: "malta", code: "+356"},
  {label: "Marshall Islands", value: "marshall-islands", code: "+692"},
  {label: "Mauritania", value: "mauritania", code: "+222"},
  {label: "Mauritius", value: "mauritius", code: "+230"},
  {label: "Mexico", value: "mexico", code: "+52"},
  {label: "Micronesia", value: "micronesia", code: "+691"},
  {label: "Moldova", value: "moldova", code: "+373"},
  {label: "Monaco", value: "monaco", code: "+377"},
  {label: "Mongolia", value: "mongolia", code: "+976"},
  {label: "Montenegro", value: "montenegro", code: "+382"},
  {label: "Morocco", value: "morocco", code: "+212"},
  {label: "Mozambique", value: "mozambique", code: "+258"},
  {label: "Myanmar", value: "myanmar", code: "+95"},
  {label: "Namibia", value: "namibia", code: "+264"},
  {label: "Nauru", value: "nauru", code: "+674"},
  {label: "Nepal", value: "nepal", code: "+977"},
  {label: "Netherlands", value: "netherlands", code: "+31"},
  {label: "New Zealand", value: "new-zealand", code: "+64"},
  {label: "Nicaragua", value: "nicaragua", code: "+505"},
  {label: "Niger", value: "niger", code: "+227"},
  {label: "Nigeria", value: "nigeria", code: "+234"},
  {label: "Norway", value: "norway", code: "+47"},
  {label: "Oman", value: "oman", code: "+968"},
  {label: "Pakistan", value: "pakistan", code: "+92"},
  {label: "Palau", value: "palau", code: "+680"},
  {label: "Palestine", value: "palestine", code: "+970"},
  {label: "Panama", value: "panama", code: "+507"},
  {label: "Papua New Guinea", value: "papua-new-guinea", code: "+675"},
  {label: "Paraguay", value: "paraguay", code: "+595"},
  {label: "Peru", value: "peru", code: "+51"},
  {label: "Philippines", value: "philippines", code: "+63"},
  {label: "Poland", value: "poland", code: "+48"},
  {label: "Portugal", value: "portugal", code: "+351"},
  {label: "Qatar", value: "qatar", code: "+974"},
  {label: "Romania", value: "romania", code: "+40"},
  {label: "Russia", value: "russia", code: "+7"},
  {label: "Rwanda", value: "rwanda", code: "+250"},
  {label: "Samoa", value: "samoa", code: "+685"},
  {label: "San Marino", value: "san-marino", code: "+378"},
  {label: "Saudi Arabia", value: "saudi-arabia", code: "+966"},
  {label: "Senegal", value: "senegal", code: "+221"},
  {label: "Serbia", value: "serbia", code: "+381"},
  {label: "Seychelles", value: "seychelles", code: "+248"},
  {label: "Sierra Leone", value: "sierra-leone", code: "+232"},
  {label: "Singapore", value: "singapore", code: "+65"},
  {label: "Slovakia", value: "slovakia", code: "+421"},
  {label: "Slovenia", value: "slovenia", code: "+386"},
  {label: "Solomon Islands", value: "solomon-islands", code: "+677"},
  {label: "Somalia", value: "somalia", code: "+252"},
  {label: "South Africa", value: "south-africa", code: "+27"},
  {label: "South Sudan", value: "south-sudan", code: "+211"},
  {label: "Spain", value: "spain", code: "+34"},
  {label: "Sri Lanka", value: "sri-lanka", code: "+94"},
  {label: "Sudan", value: "sudan", code: "+249"},
  {label: "Suriname", value: "suriname", code: "+597"},
  {label: "Sweden", value: "sweden", code: "+46"},
  {label: "Switzerland", value: "switzerland", code: "+41"},
  {label: "Syria", value: "syria", code: "+963"},
  {label: "Taiwan", value: "taiwan", code: "+886"},
  {label: "Tajikistan", value: "tajikistan", code: "+992"},
  {label: "Tanzania", value: "tanzania", code: "+255"},
  {label: "Thailand", value: "thailand", code: "+66"},
  {label: "Timor‑Leste", value: "timor-leste", code: "+670"},
  {label: "Togo", value: "togo", code: "+228"},
  {label: "Tonga", value: "tonga", code: "+676"},
  {label: "Trinidad and Tobago", value: "trinidad-and-tobago", code: "+1-868"},
  {label: "Tunisia", value: "tunisia", code: "+216"},
  {label: "Turkey", value: "turkey", code: "+90"},
  {label: "Turkmenistan", value: "turkmenistan", code: "+993"},
  {label: "Tuvalu", value: "tuvalu", code: "+688"},
  {label: "Uganda", value: "uganda", code: "+256"},
  {label: "Ukraine", value: "ukraine", code: "+380"},
  {label: "United Arab Emirates", value: "united-arab-emirates", code: "+971"},
  {label: "United Kingdom", value: "united-kingdom", code: "+44"},
  {label: "United States", value: "united-states", code: "+1"},
  {label: "Uruguay", value: "uruguay", code: "+598"},
  {label: "Uzbekistan", value: "uzbekistan", code: "+998"},
  {label: "Vanuatu", value: "vanuatu", code: "+678"},
  {
    label: "Vatican City",
    value: "vatican-city",
    code: "+379" /* برخی منابع مختلف است */,
  },
  {label: "Venezuela", value: "venezuela", code: "+58"},
  {label: "Vietnam", value: "vietnam", code: "+84"},
  {label: "Yemen", value: "yemen", code: "+967"},
  {label: "Zambia", value: "zambia", code: "+260"},
  {label: "Zimbabwe", value: "zimbabwe", code: "+263"},
];

export const all_countries_code = [
  {code: "+93", label: "Afghanistan"},
  {code: "+355", label: "Albania"},
  {code: "+213", label: "Algeria"},
  {code: "+1-684", label: "American Samoa"},
  {code: "+376", label: "Andorra"},
  {code: "+244", label: "Angola"},
  {code: "+1-264", label: "Anguilla"},
  {code: "+1-268", label: "Antigua and Barbuda"},
  {code: "+54", label: "Argentina"},
  {code: "+374", label: "Armenia"},
  {code: "+297", label: "Aruba"},
  {code: "+61", label: "Australia"},
  {code: "+43", label: "Austria"},
  {code: "+994", label: "Azerbaijan"},
  {code: "+1-242", label: "Bahamas"},
  {code: "+973", label: "Bahrain"},
  {code: "+880", label: "Bangladesh"},
  {code: "+1-246", label: "Barbados"},
  {code: "+375", label: "Belarus"},
  {code: "+32", label: "Belgium"},
  {code: "+501", label: "Belize"},
  {code: "+229", label: "Benin"},
  {code: "+975", label: "Bhutan"},
  {code: "+591", label: "Bolivia"},
  {code: "+387", label: "Bosnia and Herzegovina"},
  {code: "+267", label: "Botswana"},
  {code: "+55", label: "Brazil"},
  {code: "+673", label: "Brunei"},
  {code: "+359", label: "Bulgaria"},
  {code: "+226", label: "Burkina Faso"},
  {code: "+257", label: "Burundi"},
  {code: "+238", label: "Cabo Verde"},
  {code: "+855", label: "Cambodia"},
  {code: "+237", label: "Cameroon"},
  {code: "+1", label: "Canada"},
  {code: "+236", label: "Central African Republic"},
  {code: "+235", label: "Chad"},
  {code: "+56", label: "Chile"},
  {code: "+86", label: "China"},
  {code: "+57", label: "Colombia"},
  {code: "+269", label: "Comoros"},
  {code: "+242", label: "Congo"},
  {code: "+243", label: "Congo, Democratic Republic of the"},
  {code: "+506", label: "Costa Rica"},
  {code: "+385", label: "Croatia"},
  {code: "+53", label: "Cuba"},
  {code: "+357", label: "Cyprus"},
  {code: "+420", label: "Czech Republic"},
  {code: "+45", label: "Denmark"},
  {code: "+253", label: "Djibouti"},
  {code: "+1-767", label: "Dominica"},
  {code: "+1-809", label: "Dominican Republic"},
  {code: "+593", label: "Ecuador"},
  {code: "+20", label: "Egypt"},
  {code: "+503", label: "El Salvador"},
  {code: "+240", label: "Equatorial Guinea"},
  {code: "+291", label: "Eritrea"},
  {code: "+372", label: "Estonia"},
  {code: "+268", label: "Eswatini"},
  {code: "+251", label: "Ethiopia"},
  {code: "+679", label: "Fiji"},
  {code: "+358", label: "Finland"},
  {code: "+33", label: "France"},
  {code: "+241", label: "Gabon"},
  {code: "+220", label: "Gambia"},
  {code: "+995", label: "Georgia"},
  {code: "+49", label: "Germany"},
  {code: "+233", label: "Ghana"},
  {code: "+30", label: "Greece"},
  {code: "+1-473", label: "Grenada"},
  {code: "+502", label: "Guatemala"},
  {code: "+224", label: "Guinea"},
  {code: "+245", label: "Guinea-Bissau"},
  {code: "+592", label: "Guyana"},
  {code: "+509", label: "Haiti"},
  {code: "+504", label: "Honduras"},
  {code: "+36", label: "Hungary"},
  {code: "+354", label: "Iceland"},
  {code: "+91", label: "India"},
  {code: "+62", label: "Indonesia"},
  {code: "+98", label: "Iran"},
  {code: "+964", label: "Iraq"},
  {code: "+353", label: "Ireland"},
  {code: "+972", label: "Israel"},
  {code: "+39", label: "Italy"},
  {code: "+1-876", label: "Jamaica"},
  {code: "+81", label: "Japan"},
  {code: "+962", label: "Jordan"},
  {code: "+7", label: "Kazakhstan"},
  {code: "+254", label: "Kenya"},
  {code: "+686", label: "Kiribati"},
  {code: "+965", label: "Kuwait"},
  {code: "+996", label: "Kyrgyzstan"},
  {code: "+856", label: "Laos"},
  {code: "+371", label: "Latvia"},
  {code: "+961", label: "Lebanon"},
  {code: "+266", label: "Lesotho"},
  {code: "+231", label: "Liberia"},
  {code: "+218", label: "Libya"},
  {code: "+423", label: "Liechtenstein"},
  {code: "+370", label: "Lithuania"},
  {code: "+352", label: "Luxembourg"},
  {code: "+853", label: "Macau"},
  {code: "+389", label: "North Macedonia"},
  {code: "+261", label: "Madagascar"},
  {code: "+265", label: "Malawi"},
  {code: "+60", label: "Malaysia"},
  {code: "+960", label: "Maldives"},
  {code: "+223", label: "Mali"},
  {code: "+356", label: "Malta"},
  {code: "+692", label: "Marshall Islands"},
  {code: "+222", label: "Mauritania"},
  {code: "+230", label: "Mauritius"},
  {code: "+52", label: "Mexico"},
  {code: "+691", label: "Micronesia"},
  {code: "+373", label: "Moldova"},
  {code: "+377", label: "Monaco"},
  {code: "+976", label: "Mongolia"},
  {code: "+382", label: "Montenegro"},
  {code: "+212", label: "Morocco"},
  {code: "+258", label: "Mozambique"},
  {code: "+95", label: "Myanmar"},
  {code: "+264", label: "Namibia"},
  {code: "+674", label: "Nauru"},
  {code: "+977", label: "Nepal"},
  {code: "+31", label: "Netherlands"},
  {code: "+64", label: "New Zealand"},
  {code: "+505", label: "Nicaragua"},
  {code: "+227", label: "Niger"},
  {code: "+234", label: "Nigeria"},
  {code: "+47", label: "Norway"},
  {code: "+968", label: "Oman"},
  {code: "+92", label: "Pakistan"},
  {code: "+680", label: "Palau"},
  {code: "+970", label: "Palestine"},
  {code: "+507", label: "Panama"},
  {code: "+675", label: "Papua New Guinea"},
  {code: "+595", label: "Paraguay"},
  {code: "+51", label: "Peru"},
  {code: "+63", label: "Philippines"},
  {code: "+48", label: "Poland"},
  {code: "+351", label: "Portugal"},
  {code: "+1-787", label: "Puerto Rico"},
  {code: "+974", label: "Qatar"},
  {code: "+40", label: "Romania"},
  {code: "+7", label: "Russia"},
  {code: "+250", label: "Rwanda"},
  {code: "+590", label: "Saint Barthélemy"},
  {code: "+1-869", label: "Saint Kitts and Nevis"},
  {code: "+1-758", label: "Saint Lucia"},
  {code: "+508", label: "Saint Pierre and Miquelon"},
  {code: "+1-784", label: "Saint Vincent and the Grenadines"},
  {code: "+685", label: "Samoa"},
  {code: "+378", label: "San Marino"},
  {code: "+239", label: "Sao Tome and Principe"},
  {code: "+966", label: "Saudi Arabia"},
  {code: "+221", label: "Senegal"},
  {code: "+381", label: "Serbia"},
  {code: "+248", label: "Seychelles"},
  {code: "+232", label: "Sierra Leone"},
  {code: "+65", label: "Singapore"},
  {code: "+421", label: "Slovakia"},
  {code: "+386", label: "Slovenia"},
  {code: "+677", label: "Solomon Islands"},
  {code: "+27", label: "South Africa"},
  {code: "+211", label: "South Sudan"},
  {code: "+34", label: "Spain"},
  {code: "+94", label: "Sri Lanka"},
  {code: "+249", label: "Sudan"},
  {code: "+597", label: "Suriname"},
  {code: "+268", label: "Swaziland"},
  {code: "+46", label: "Sweden"},
  {code: "+41", label: "Switzerland"},
  {code: "+963", label: "Syria"},
  {code: "+886", label: "Taiwan"},
  {code: "+992", label: "Tajikistan"},
  {code: "+255", label: "Tanzania"},
  {code: "+66", label: "Thailand"},
  {code: "+670", label: "Timor‑Leste"},
  {code: "+228", label: "Togo"},
  {code: "+676", label: "Tonga"},
  {code: "+1-868", label: "Trinidad and Tobago"},
  {code: "+216", label: "Tunisia"},
  {code: "+90", label: "Turkey"},
  {code: "+993", label: "Turkmenistan"},
  {code: "+688", label: "Tuvalu"},
  {code: "+256", label: "Uganda"},
  {code: "+380", label: "Ukraine"},
  {code: "+971", label: "United Arab Emirates"},
  {code: "+44", label: "United Kingdom"},
  {code: "+1", label: "United States"},
  {code: "+598", label: "Uruguay"},
  {code: "+998", label: "Uzbekistan"},
  {code: "+678", label: "Vanuatu"},
  {code: "+39‑89", label: "Vatican City"},
  {code: "+58", label: "Venezuela"},
  {code: "+84", label: "Vietnam"},
  {code: "+967", label: "Yemen"},
  {code: "+260", label: "Zambia"},
  {code: "+263", label: "Zimbabwe"},
];

export const default_info = {
  phone_number: "+989385725269",
  email: "ipd@shomal.hospital",
};
export const pages_titles = {
  contact_us: {
    fa: "تماس با ما",
    en: "Contact Us",
    ar: "اتصل بنا",
  },
  doctors: {
    fa: "پزشکان",
    en: "Doctors",
    ar: "الأطباء",
  },
  medical_services: {
    fa: "خدمات پزشکی",
    en: "Medical Services",
    ar: "الخدمات الطبية",
  },
  patient_rights_charter: {
    fa: "منشور حقوق بیمار",
    en: "Patient Rights Charter",
    ar: "ميثاق حقوق المرضى",
  },
  pricing: {
    fa: "قیمت‌ها",
    en: "Pricing",
    ar: "الأسعار",
  },
  transfer_services: {
    fa: "خدمات ترانسفر",
    en: "Transfer Services",
    ar: "خدمات النقل",
  },
  upload_documents: {
    fa: "آپلود مدارک",
    en: "Upload Documents",
    ar: "تحميل المستندات",
  },
  about_us: {
    fa: "درباره ما",
    en: "About Us",
    ar: "معلومات عنا",
  },
};
